export const sampleData = {"location":{"name":"Tokyo","region":"Tokyo","country":"Japan","lat":35.69,"lon":139.69,"tz_id":"Asia/Tokyo","localtime_epoch":1716546022,"localtime":"2024-05-24 19:20"},"current":{"last_updated_epoch":1716545700,"last_updated":"2024-05-24 19:15","temp_c":23.0,"temp_f":73.4,"is_day":0,"condition":{"text":"Clear","icon":"//cdn.weatherapi.com/weather/64x64/night/113.png","code":1000},"wind_mph":12.5,"wind_kph":20.2,"wind_degree":180,"wind_dir":"S","pressure_mb":1004.0,"pressure_in":29.65,"precip_mm":0.0,"precip_in":0.0,"humidity":69,"cloud":0,"feelslike_c":24.9,"feelslike_f":76.8,"vis_km":10.0,"vis_miles":6.0,"uv":1.0,"gust_mph":17.4,"gust_kph":28.0}}
export const cities = [
    'Tokyo',
    'New York City',
    'London',
    'Paris',
    'Beijing',
    'Moscow',
    'Sao Paulo',
    'Mumbai',
    'Istanbul',
    'Shanghai',
    'Los Angeles',
    'Buenos Aires',
    'Cairo',
    'Lagos',
    'Jakarta',
    'Seoul',
    'Karachi',
    'Mexico City',
    'Dhaka',
    'Osaka',
    'Manila',
    'Rio de Janeiro',
    'Delhi',
    'Guangzhou',
    'Kolkata',
    'Lahore',
    'Kinshasa',
    'Tehran',
    'Bangkok',
    'Baghdad',
    'Lima',
    'Bogota',
    'Johannesburg',
    'Santiago',
    'Toronto',
    'Ho Chi Minh City',
    'Hong Kong',
    'Bangalore',
    'Chennai',
    'Miami',
    'Hyderabad',
    'Riyadh',
    'Singapore',
    'Atlanta',
    'Kabul',
    'Berlin',
    'Barcelona',
    'Jeddah',
    'Madrid',
    'Nairobi',
    'Kuala Lumpur',
    'Washington D.C.',
    'Vienna',
    'Rome',
    'Amsterdam',
    'Warsaw',
    'San Francisco',
    'Sydney',
    'Melbourne',
    'Montreal',
    'Copenhagen',
    'Athens',
    'Budapest',
    'Stockholm',
    'Prague',
    'Dubai',
    'Bucharest',
    'Helsinki',
    'Oslo',
    'Brussels',
    'Lisbon',
    'Jerusalem',
    'Dublin',
    'Vancouver',
    'San Diego',
    'Seattle',
    'Perth',
    'Austin',
    'Denver',
    'Phoenix',
    'Dallas',
    'Philadelphia',
    'Detroit',
    'Minneapolis',
    'Manchester',
    'Birmingham',
    'Liverpool',
    'Glasgow',
    'Leeds',
    'Sheffield',
    'Bristol',
    'Edinburgh',
    'Leicester',
    'Belfast'
  ];

  